spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: truels

        format_sql: true
#        default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

file:
  dir:
    video: C:/Users/jake9/indi/videoFile
    thumbnail: C:/Users/jake9/indi/thumbNailFile
    profile: C:/Users/jake9/indi/profile

cloud:
  aws:
    s3:
      bucket: indi-bucket
      profile-folder : profile
      video-folder: videoFile
      thumbNail-folder: thumbNailFile
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAQKMWVNZ6X4DHJDHB
      secret-key: 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


#  file.dir=C:/Users/jake9/Spring/Spring MVC_2/file/