spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/indi
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

file:
  dir:
    video: C:/Users/jake9/indi/videoFile
    thumbnail: C:/Users/jake9/indi/thumbNailFile
    profile: C:/Users/jake9/indi/profile



#  file.dir=C:/Users/jake9/Spring/Spring MVC_2/file/